apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-gitops-demo-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://prod-example-cluster.hcp.canadacentral.azmk8s.io:443
  project: default
  source:
    path: gitops-demo/overlays/prod
    repoURL: git@github.com:muntashir-islam/cicd-GitOps-Jenkins-Argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-gitops-demo-test
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://test-example-cluster.hcp.canadacentral.azmk8s.io:443
  project: default
  source:
    path: gitops-demo/overlays/test
    repoURL: git@github.com:muntashir-islam/cicd-GitOps-Jenkins-Argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true