apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
    version: v1.0
  name: demo
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
        version: v1.0
    spec:
      containers:
        - env:
            - name: INSTANA_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          image: hishabdev/demo:master-a5d1185be7e26823cc8182a984c5f8de4b37cdc0
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 20
            tcpSocket:
              port: 8080
          name: demo
          ports:
            - containerPort: 8080
              name: http-query
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 15
            tcpSocket:
              port: 8080
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
      imagePullSecrets:
        - name: hishab-image