apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
    version: v1.0
  name: demo
  namespace: test
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: demo
      containers:
      - name: demo
        resources:
          limits:
            cpu: 600m
            memory: 600Mi